<?php
/**
 * Created by PhpStorm.
 * User: Julian Albero
 * Date: 15/07/2015
 * Time: 08:33 PM
 */

$_POST['selectTipoDocumento'];
$_POST['fechaencuesta'];
$_POST['inpNumDocuemnto'];
$_POST['inpNombreRazonSocial'];
$_POST['telefonoEmpresa'];
$_POST['celularEmpresa'];
$_POST['correoEmpresa'];
$_POST['inpNombreRepresentante'];
$_POST['direccionEmpresa'];
$_POST['barrioEmpresa'];
$_POST['tipoOrg'];
$_POST['selectUbicaComercial'];
$_POST['clasificacionEmpresa'];
$_POST['tieneEmpleados'];
$_POST['tipoEmpleados'];
$_POST['numEmpleados'];
$_POST['afilPensSalud'];
$_POST['justificacionPrestaciones'];
$_POST['registMercant'];
$_POST['justificacionMercantil'];
$_POST['numMatriculaMercantil'];
$_POST['anioMatriculaMercantil'];
$_POST['permiSuelo'];
$_POST['justificacionUsoSuelo'];
$_POST['certBomberos'];
$_POST['justificacionBomberos'];
$_POST['manipAlimentos'];
$_POST['justificacionManipulacionAlimentos'];
$_POST['regisInvima'];
$_POST['justificacionInvima'];
$_POST['numInvima'];
$_POST['fechaInvima'];
$_POST['certSayAcin'];
$_POST['justificacionSaycoAcinpro'];
$_POST['numSayco'];
$_POST['fechaAcinpro'];
$_POST['contrDispoResid'];
$_POST['numResiduosPeligrosos'];
$_POST['fechaResiduosPeligrosos'];
$_POST['numCodCiiu'];
$_POST['codIndustComerc'];
$_POST['numIndustriaComercio'];
$_POST['valorIngresosMensuales'];
$_POST['valorActivosEmpresa'];
$_POST['permisoTic'];
$_POST['permisoFuncionamiento'];
$_POST['otroPermisoFunconamiento'];
$_POST['pagaImpuesto'];
$_POST['otroImpuesto'];
$_POST['afiliadoSaludPensionArl'];
$_POST['numMaquinas'];
$_POST['tieneSeguridadPriv'];
$_POST['tipoSistemaSeguridad'];
$_POST['victimaDelito'];
$_POST['tipoDelito'];
$_POST['segPersonal'];